apiVersion: batch/v1
kind: Job
metadata:
  name: anagram-job
  namespace: anagram
spec:
  template:
    spec:
      containers:
      - name: anagram-finder
        image: salihbozkaya1001/anagram-finder:latest 
        command: ["/app/anagram-finder", "anagrams.txt"]
      restartPolicy: Never
  backoffLimit: 3